### PR TITLE
issues/191

### LINKED ISSUE #191: Proposal: change `prep` to use the original corpus size consistently.
Looking at prep, it is strange that the percentages change each time the commmand is re-run. In order to guarantee consistent percentages, the numbers from the original, unfiltered corpus should be stored and used.

### PR DESCRIPTION
**Pull request by JaimieMurdock**
This pull request contains a significant change to `topicexplorer prep`:
- `topicexplorer init` no longer removes words occurring less than 5 times and no longer applies the english nltk stoplist automatically.
- `topicexplorer prep` may now only be run once
- All percentages are calculated based on the original unstopped length.
- There are two new flags enabling percentages of the corpus to be shaved off the top and bottom: `--high-percent` and `--low-percent`

These effectively close #191 

The unit tests for Windows are not currently working. I will be addressing this in a separate issue and PR.

# Notes on the new system of pull requests
This is a pull request in our new system of releases, moving from a feature branch to the `develop` branch. To get to this point, I selected the "Branches" icon on the main repo page:

image

Once on that page, I can file a pull request from the branch directly. New commits to the branch are automatically assigned to the pull request. In order to merge to the `develop` branch, rather than `master`, I had to select it under "base:"

image

--

The pull request contains a mechanism for reviewing the code - you can either do a summary review or make line-by-line comments. It's pretty helpful. I've requested a review from Colin, but anyone can review.

When pulling into a protected branch, like `master`, we can require a code review to make sure we don't introduce regressions. We can also require that the unit tests pass.

### CODE REVIEW

**Comment by colinallen** [comment]
How concerned should I be about code check failures?

**Comment by JaimieMurdock** [comment]
Very concerned, since it was all of the tests!

In general, travis-ci indicates whether it will run on Linux/macOS. Appveyor indicates whether it will run on Windows. The `/pr` indicates success of the pull request, `/branch` or `/push` indicates the success of the last commit.

I'll look at the test cases later this afternoon and see what is failing.

**Comment by JaimieMurdock** [comment]
I suspect that I hadn't pushed the newest changes to `vsm` to PyPI yet.

**Comment by JaimieMurdock** [comment]
The missing `vsm` changes are it:

```
Traceback (most recent call last):
  File "/home/travis/build/inpho/topic-explorer/topicexplorer/demo.py", line 112, in <module>
    main(launch=launch)
  File "/home/travis/build/inpho/topic-explorer/topicexplorer/demo.py", line 86, in main
    prep.main(args)
  File "topicexplorer/prep.py", line 340, in main
    if c.original_length != len(c.corpus):
AttributeError: 'Corpus' object has no attribute 'original_length'
```

**Comment by JaimieMurdock** [comment]
I've fixed the Appveyor checks so we are ready to merge!

**Pull request merged**
